use_frameworks!

platform :ios, '10.0'

target 'XCAlphaVideoPlayer_Example' do
  pod 'XCAlphaVideoPlayer', :path => '../'

  target 'XCAlphaVideoPlayer_Tests' do
    inherit! :search_paths

    
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
